logsBucket: "gs://cloud-a3-jaykumar-logs"
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/container2:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/container2:latest",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials my-cluster --zone us-central1-a --project $PROJECT_ID
        kubectl set image deployment/container2 container2=us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/container2:latest
